listenAddress: ":9000"
machineId: 1

socketIo:
  readTimeout: 5s
  writeTimeout: 5s
  pingTimeout: 25s
  pingInterval: 20s
  readBufferSize: 1024
  writeBufferSize: 1024

nsq:
  address: 127.0.0.1:4150
  messageTopic: "im_message"

redis:
  address: 127.0.0.1:6379
  password: "238XSfh98xa"
  db: 1
  keyPrefix: "socket.io"
  timeout: 60s
  poolSize: 10
  minIdleConn: 1
  maxIdleConn: 5


authCheck:
  enable: true
  httpUrl: http://localhost:8081/internal/api/websocket-auth
  responseCode: 200
  timeout: 60s