services:
  socket-server:
    image: socket-server:latest
    volumes:
      - ./prod/config.yaml:/app/config.yaml
    command:
      - /app/app
    ports:
      - "9000:9000"
    restart: always
    networks:
      - kf_network

networks:
  kf_network:
    external: true
