machineId: 1
listenAddress: ":9000"

socketIo:
  readTimeout: 5s
  writeTimeout: 5s
  pingTimeout: 25s
  pingInterval: 20s
  readBufferSize: 1024
  writeBufferSize: 1024

nsq:
  address: nsq:4150
  messageTopic: "im_message"

authCheck:
  enable: false
  httpUrl: http://kf-api:8000/xxx
  responseCode: 200
  timeout: 60s

redis:
  address: redis:6379
  password: "238XSfh98xa"
  db: 1
  keyPrefix: "socket.io"
  timeout: 60s
  poolSize: 10
  minIdleConn: 1
  maxIdleConn: 5

log:
  level: info
  format: json